project_id = "vwylsusacaucxyphbxad"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
port = 54327
file_size_limit = "50MiB"
image_transformation = true

[edge_runtime]
enabled = true
port = 54328

[functions.analytics]

[functions.auto-scheduler]

[functions.generate-ai-replies]

[functions.post-to-twitter]

[functions.send-confirmation-email]

[functions.test-credentials]

[functions.test-twitter-auth]

[functions.update-platform-secrets]

[functions.update-twitter-secrets]