name: Deploy Supabase Edge Functions

on:
  push:
    branches: [ main ]
    paths:
      - 'supabase/functions/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Supabase CLI
      uses: supabase/setup-cli@v1
      with:
        version: latest

    - name: Verify environment variables
      run: |
        echo "PROJECT_ID length: ${#PROJECT_ID}"
        echo "PROJECT_ID format: ${PROJECT_ID:0:8}..."
        echo "ACCESS_TOKEN format: ${SUPABASE_ACCESS_TOKEN:0:4}..."
        echo "ACCESS_TOKEN length: ${#SUPABASE_ACCESS_TOKEN}"
      env:
        SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        PROJECT_ID: ${{ secrets.PROJECT_ID }}

    - name: Test Supabase authentication
      run: |
        echo "Testing Supabase CLI authentication..."
        supabase --version
        supabase projects list
      env:
        SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

    - name: Deploy functions with verbose output
      run: |
        echo "Starting deployment..."
        supabase functions deploy --project-ref ${{ secrets.PROJECT_ID }} --debug
      env:
        SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
